apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
labels:
    app: {{ template "fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}